unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-h resize-pane -L 10
bind -n M-j resize-pane -D 10
bind -n M-k resize-pane -U 10
bind -n M-l resize-pane -R 10
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
